apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        front-tier: "true"
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/kubernetes-maillard-frossard/voting-images/nginx
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP