apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
spec:
  template:
    spec:
      containers:
        - name: seed-data
          image: europe-west9-docker.pkg.dev/kubernetes-maillard-frossard/voting-images/seed
      restartPolicy: Never
  backoffLimit: 0